# Generated by Django 4.2.7 on 2025-10-05 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_api_user_email_a7eefd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid PH mobile number (e.g., 09171234567 or +639171234567)', regex='^(09|\\+639)\\d{9}$')])),
                ('facebook', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['phone'], name='api_anonymo_phone_9b7821_idx'), models.Index(fields=['session_id'], name='api_anonymo_session_10cf0b_idx'), models.Index(fields=['is_active', '-last_seen'], name='api_anonymo_is_acti_92083e_idx')],
            },
        ),
    ]
