# Generated by Django 4.2.7 on 2025-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anonymouslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouslocation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous_locations/'),
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='supply_needs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
