# Generated by Django 4.2.7 on 2025-10-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_anonymouslocation_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouslocation',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='last_name',
            field=models.CharField(default="''", max_length=100),
            preserve_default=False,
        ),
    ]
