# Generated by Django 4.2.7 on 2025-10-05 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_anonymouslocation_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorOnTheWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('arrived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-marked_at'],
            },
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='donated_by_user',
            field=models.ForeignKey(blank=True, help_text='Donator who scanned the QR code', limit_choices_to={'role': 'donator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_donations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='donation_received',
            field=models.BooleanField(default=False, help_text='Whether this location has received donation'),
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='donation_timestamp',
            field=models.DateTimeField(blank=True, help_text='When the donation was received', null=True),
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='next_request_allowed_at',
            field=models.DateTimeField(blank=True, help_text='When this phone can create another request (3 hours after donation)', null=True),
        ),
        migrations.AddField(
            model_name='anonymouslocation',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique QR code for donators to scan', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='anonymouslocation',
            index=models.Index(fields=['qr_code'], name='api_anonymo_qr_code_eaea63_idx'),
        ),
        migrations.AddField(
            model_name='donatorontheway',
            name='donator',
            field=models.ForeignKey(limit_choices_to={'role': 'donator'}, on_delete=django.db.models.deletion.CASCADE, related_name='helping_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donatorontheway',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donators_on_the_way', to='api.anonymouslocation'),
        ),
        migrations.AlterUniqueTogether(
            name='donatorontheway',
            unique_together={('location', 'donator')},
        ),
    ]
