# Generated by Django 4.2.7 on 2025-10-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_donatorontheway_anonymouslocation_donated_by_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_first_name', models.CharField(max_length=100)),
                ('affected_last_name', models.CharField(max_length=100)),
                ('affected_phone', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('supply_needs_fulfilled', models.JSONField(blank=True, default=dict)),
                ('qr_code', models.CharField(db_index=True, max_length=100)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('donator', models.ForeignKey(limit_choices_to={'role': 'donator'}, on_delete=django.db.models.deletion.CASCADE, related_name='qr_donations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donation History',
                'ordering': ['-donated_at'],
                'indexes': [models.Index(fields=['donator', '-donated_at'], name='api_donatio_donator_02b649_idx'), models.Index(fields=['-donated_at'], name='api_donatio_donated_096395_idx')],
            },
        ),
    ]
