# Generated by Django 4.2.7 on 2025-10-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_donationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], null=True)),
                ('comment', models.TextField(blank=True)),
                ('supplies_confirmed', models.JSONField(blank=True, default=dict)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('donation_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.donationhistory')),
            ],
            options={
                'verbose_name_plural': 'Donation Ratings',
                'ordering': ['-rated_at'],
            },
        ),
    ]
