# Generated by Django 4.2.7 on 2025-10-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_donationrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatorontheway',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donatorontheway',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.FloatField(help_text='Location accuracy in meters')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donator_on_the_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='api.donatorontheway')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['donator_on_the_way', '-timestamp'], name='api_locatio_donator_ef5a25_idx')],
            },
        ),
    ]
