# Generated by Django 4.2.7 on 2025-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_donatorontheway_is_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouslocation',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='anonymouslocation',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='anonymouslocation',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
